version: '3.8'

services:
  client:
    image: img2url-client
    container_name: img2url-client
    build: 
      context: ./client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client:/app
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - server

  server:
    image: img2url-server
    container_name: img2url-server
    build:
      context: ./server
    networks:
      - app-network
    expose:
      - "8000"


networks:
  app-network:
    driver: bridge