version: '3.8'

services:
  client:
    image: img2url-client
    container_name: img2url-client
    build: 
      context: ./client  # or ./frontend depending on your folder structure
    networks:
      - app-network
    ports:
      - "80:80"  # Map host port 3000 to container port 80
    depends_on:
      - server

  server:
    image: img2url-server
    container_name: img2url-server
    build:
      context: ./server  # or ./backend depending on your folder structure
    networks:
      - app-network
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    environment:
      - DATABASE_URL=${DATABASE_URL}

networks:
  app-network:
    driver: bridge