version: '3.8'

services:
  client:
    build:
      context: ./client
      args:
        VITE_API_BASE_URL: http://backend:8000
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
